# Generated by Django 5.2.5 on 2026-06-09 19:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(blank=True, max_length=200, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('type', models.CharField(blank=True, choices=[('charity', 'Charity'), ('cooperative', 'Cooperative'), ('foundation', 'Foundation'), ('franchise', 'Franchise'), ('holding company', 'Holding Company'), ('joint venture', 'Joint Venture'), ('limited liability company', 'Limited Liability Company'), ('multinational corporation', 'Multinational Corporation')], max_length=1000)),
                ('industry', models.CharField(blank=True, choices=[('advertising & media', 'Advertising & Media'), ('agriculture & farming', 'Agriculture & Farming'), ('automotive sales & leasing', 'Automotive Sales & Leasing'), ('constructure & engineering', 'Constructure & Engineering'), ('cryptocurrency exchange', 'Cryptocurrency Exchange'), ('cryptocurrency services', 'Cryptocurrency Services'), ('e-commerce', 'E-commerce')], max_length=1000)),
                ('purpose', models.TextField(blank=True, choices=[('sending and receiving funds for business services ', 'Sending and receiving funds for business services '), ('paying staffs', 'Paying staffs'), ('holding FX to protect business profit from currency fluctuations', 'Holding FX to protect business profit from currency fluctuations')])),
                ('argrement', models.BooleanField(default=False)),
                ('businessVerified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='user email')),
                ('token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('avatar', models.FileField(blank=True, null=True, unique=True, upload_to='avatars/', verbose_name='useravatar')),
                ('avatarUrl', models.URLField(blank=True, null=True, unique=True)),
                ('phoneNumber', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('country', models.CharField(blank=True, null=True)),
                ('accountType', models.CharField(blank=True, choices=[('savings', 'Savings'), ('current', 'Current'), ('fixed deposit', 'Fixed Deposit'), ('business', 'Business'), ('investment', 'investment')], default='savings', null=True)),
                ('refCode', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('address1', models.TextField(blank=True, null=True)),
                ('address2', models.TextField(blank=True, null=True)),
                ('nidCard', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('isVerifiedCompleted', models.IntegerField(default=2)),
                ('nidImagefront', models.FileField(blank=True, null=True, unique=True, upload_to='users/NidImages/front/')),
                ('nidImageback', models.FileField(blank=True, null=True, unique=True, upload_to='users/NidImages/back/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('isBusinessAccount', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leadbankapp.businessusers')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
