# Generated by Django 5.2.5 on 2026-06-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadbankapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='isVerifiedCompleted',
            field=models.IntegerField(default=0),
        ),
    ]
