# Generated by Django 5.2.5 on 2026-06-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadbankapp', '0002_alter_user_managers_alter_user_isverifiedcompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ssnNumber',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
