# Generated by Django 5.2.5 on 2026-06-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadbankapp', '0003_user_ssnnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middleName',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
