# Generated by Django 5.2.5 on 2026-06-13 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadbankapp', '0004_user_middlename'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='transactionPin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('currencycode', models.CharField(blank=True, max_length=2, null=True)),
                ('currencyName', models.CharField(blank=True, max_length=100, null=True)),
                ('account_active', models.BooleanField(default=False)),
                ('accountNumber', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('accountToken', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('achRoutingNumber', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('iban', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('sortCode', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
