# Generated by Django 5.2.5 on 2026-06-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadbankapp', '0005_user_otp_user_transactionpin_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
