# Generated by Django 5.2.5 on 2026-06-14 20:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadbankapp', '0006_account_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='businessusers',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencySign', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.BigIntegerField(default=0)),
                ('type', models.CharField(blank=True, choices=[('withdraw', 'Withdraw'), ('deposite', 'Deposite'), ('bills', 'Bills')], max_length=50, null=True)),
                ('destination', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('success', 'Success'), ('pending', 'Pending'), ('failed', 'Failed')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leadbankapp.account')),
            ],
        ),
    ]
