# Generated by Django 5.2.5 on 2026-06-15 19:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadbankapp', '0007_account_created_at_alter_businessusers_createddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('visa', 'Visa'), ('verve', 'Verve'), ('mastercard', 'MasterCard')], max_length=100, null=True)),
                ('cardNumber', models.BigIntegerField(default=0)),
                ('cvv', models.IntegerField(default=0)),
                ('expiryDate', models.DateTimeField(blank=True, null=True)),
                ('billingAddress', models.TextField(blank=True, default='65 Charlotte Road, Hackney, London EC2A 3PE, United Kingdom', null=True)),
                ('zipcode', models.CharField(blank=True, default='EC2A 3PE', max_length=100, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('frozen', models.BooleanField(default=False)),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
