# Generated by Django 5.2.5 on 2026-06-16 21:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadbankapp', '0008_alter_accounttransaction_amount_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-createdDate']},
        ),
        migrations.CreateModel(
            name='CardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencySign', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('type', models.CharField(blank=True, choices=[('withdraw', 'Withdraw'), ('deposite', 'Deposite'), ('bills', 'Bills')], max_length=50, null=True)),
                ('destination', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('success', 'Success'), ('pending', 'Pending'), ('failed', 'Failed')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leadbankapp.card')),
            ],
        ),
    ]
