# Generated by Django 5.2.5 on 2026-06-17 08:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadbankapp', '0009_alter_card_options_cardtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supportPhone', models.CharField(max_length=20, unique=True, verbose_name='phone number with countrycode')),
                ('supportEmail', models.EmailField(max_length=254, unique=True)),
                ('chatLink', models.URLField(unique=True, verbose_name='whatsapp chat link')),
            ],
        ),
        migrations.AlterModelOptions(
            name='accounttransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cardtransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Paymentway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentType', models.CharField(blank=True, choices=[('blockchain payment', 'Blockchain Payment'), ('bank payment', 'Bank Payment')], max_length=100, null=True)),
                ('coinName', models.CharField(max_length=200, verbose_name='cryptocoin name or bankname if bank payment')),
                ('walletAddress', models.CharField(blank=True, max_length=5000, null=True, unique=True, verbose_name='wallet address or bank account number')),
                ('tokenNetwork', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leadbankapp.company')),
            ],
        ),
    ]
