# Generated by Django 5.2.5 on 2026-06-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadbankapp', '0010_company_alter_accounttransaction_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nidCard',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ssnNumber',
        ),
        migrations.AddField(
            model_name='user',
            name='ProofOfAddressDoc',
            field=models.FileField(blank=True, null=True, upload_to='users/proof_of_address/'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cityOfBirth',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='countryOfBirth',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='documentType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='zipCode',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
