# Generated by Django 5.2.5 on 2026-06-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadbankapp', '0011_remove_user_nidcard_remove_user_ssnnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
