# Generated by Django 5.2.5 on 2026-06-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadbankapp', '0012_user_is_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountNumber',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='achRoutingNumber',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='sortCode',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='cardNumber',
            field=models.CharField(blank=True, default=0, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(blank=True, default=0, max_length=200, null=True, unique=True),
        ),
    ]
