# Generated by Django 5.2.5 on 2026-06-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadbankapp', '0013_alter_account_accountnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='transactionPin',
            field=models.CharField(blank=True, null=True),
        ),
    ]
