# Generated by Django 5.2.5 on 2026-06-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadbankapp', '0014_alter_user_transactionpin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatars/', verbose_name='useravatar'),
        ),
    ]
