# Generated by Django 5.2.5 on 2026-06-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadbankapp', '0015_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='type',
            field=models.CharField(blank=True, choices=[('withdraw', 'Withdraw'), ('deposit', 'Deposit'), ('bills', 'Bills')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='billingAddress',
            field=models.TextField(blank=True, default='651 N Broad Street, Suite 206, Middletown, DE 19700, United States', null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='zipcode',
            field=models.CharField(blank=True, default='19700', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nidImageback',
            field=models.FileField(blank=True, null=True, upload_to='users/NidImages/back/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nidImagefront',
            field=models.FileField(blank=True, null=True, upload_to='users/NidImages/front/'),
        ),
    ]
