# Generated by Django 5.2.5 on 2026-06-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadbankapp', '0016_alter_accounttransaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middleName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
