# Generated by Django 5.2.5 on 2026-06-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadbankapp', '0017_alter_user_middlename'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransaction',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='type',
            field=models.CharField(blank=True, choices=[('withdraw', 'Withdraw'), ('deposit', 'Deposit'), ('bills', 'Bills')], max_length=50, null=True),
        ),
    ]
