# Generated by Django 5.2.5 on 2026-06-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadbankapp', '0018_accounttransaction_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='status',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('pending', 'Pending'), ('failed', 'Failed'), ('reversed', 'reversed')], max_length=50, null=True),
        ),
    ]
